In [1]:
from __future__ import print_function

In [2]:
import torch

In [3]:
x=torch.rand(5,3)

In [4]:
x


tensor([[0.5487, 0.2887, 0.6484],
        [0.0515, 0.4624, 0.7599],
        [0.7579, 0.9750, 0.9352],
        [0.9072, 0.5695, 0.4110],
        [0.1055, 0.6237, 0.9207]])

In [5]:
x=torch.empty(5,4)

In [6]:
x

tensor([[-6.6080e+31,  3.0813e-41,  0.0000e+00,  0.0000e+00],
        [ 3.2039e-24,  4.5601e-41,  2.6962e-19,  4.5601e-41],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [8]:
x=torch.tensor([1,2])


In [9]:
x

tensor([1, 2])

In [10]:
y=torch.tensor([3,4])

In [11]:
y

tensor([3, 4])

In [12]:
x+y

tensor([4, 6])

In [13]:
x.add(y)

tensor([4, 6])

In [14]:
x.size()

torch.Size([2])

In [15]:
x=torch.rand(5,3)

In [16]:
x

tensor([[0.6547, 0.4696, 0.1484],
        [0.0381, 0.4661, 0.5221],
        [0.0584, 0.4760, 0.8562],
        [0.4137, 0.0778, 0.0036],
        [0.9310, 0.2305, 0.3615]])

In [20]:
y=x.view(-1,15)
print(y.size())
print(y)

torch.Size([1, 15])
tensor([[0.6547, 0.4696, 0.1484, 0.0381, 0.4661, 0.5221, 0.0584, 0.4760, 0.8562,
         0.4137, 0.0778, 0.0036, 0.9310, 0.2305, 0.3615]])


In [24]:
x.size()
torch.tensor(x).dtype

/home/kaustubh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


torch.float32

In [25]:
a=torch.randn(1,2)

In [26]:
a


tensor([[-0.0401, -1.2381]])

In [27]:
features=torch.randn((1,5))

In [28]:
features

tensor([[ 1.1376, -0.9354,  0.1450, -0.4857, -0.4413]])

In [29]:
f=torch.randn(1,5)

In [30]:
f

tensor([[ 0.2616, -1.9180, -2.0306, -0.7306,  1.3364]])